### ISSUE TITLE
[ETH] The Safe SDK could not be initialized; Failed to fetch error

### ISSUE THREAD

**Issue by Claire-serveth** [5afe/safe-support#467]
### Issue Category

Safe loading issue, doesnt load on any interface

### What happened?

Getting this error when trying to initiate (and execute) a removeOwner transaction; user is on "Confirm transaction" page while
 Execute/Sign button is grayed out: 

_This transaction will most likely fail. To save gas costs, avoid confirming the transaction.
The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up._

Console logs:

```
console.js:36 [Spindl SDK] request failed TypeError: Failed to fetch
at fetch.js:43:1
at attribution.production.esm.js:1:4451
at attribution.production.esm.js:1:2337
at Object.next (attribution.production.esm.js:1:2414)
at attribution.production.esm.js:1:1339
at new Promise (<anonymous>)
at az (attribution.production.esm.js:1:1100)
at n (attribution.production.esm.js:1:4360)
at attribution.production.esm.js:1:5118
at attribution.production.esm.js:1:4819
at attribution.production.esm.js:1:2337
at Object.next (attribution.production.esm.js:1:2414)
at s (attribution.production.esm.js:1:1160)
(anonymous) @ console.js:36
Show 1 more frame
Show less
o4507209696739328.ingest.de.sentry.io/api/4507215200256080/envelope/?sentry_key=12cd7127f9cfb1cddab1f354252074b7&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.91.0:1
​
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
o4507209696739328.ingest.de.sentry.io/api/4507215200256080/envelope/?sentry_key=12cd7127f9cfb1cddab1f354252074b7&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.91.0:1
​
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
console.js:36 Code 103: Error creating a SafeTransaction (The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up.)
(anonymous) @ console.js:36
Show 1 more frame
Show less
o4507209696739328.ingest.de.sentry.io/api/4507215200256080/envelope/?sentry_key=12cd7127f9cfb1cddab1f354252074b7&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.91.0:1
​
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fetch.js:41
​
POST https://o4507209696739328.ingest.de.sentry.io/api/4507215200256080/envelope/?sentry_key=12cd7127f9cfb1cddab1f354252074b7&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.91.0 net::ERR_BLOCKED_BY_CLIENT
```

User owner wallet: eth:0x6860f6d1F8829FD8dBE9Bf20FC5B5922a46Bd647
Using ledger module
Safe address: https://app.safe.global/transactions/queue?safe=eth:0x84AE80c522C2a0FdB26E63f2AE527755d0000B81

Tried basic TS, changing wallet RPC but issue still persists.

### Date and time this happened or you first noticed this issue

20-06-2024

### Network

Ethereum Mainnet

### Safe Address

eth:0x84AE80c522C2a0FdB26E63f2AE527755d0000B81

### Token Type

None

**Comment by liliya-soroka** [comment]
we need more details about the issue and how to reproduce it . Added note with questions to the intercom

**Comment by Claire-serveth** [comment]
Thank you @liliya-soroka will definitely update here as soon as we get the response from the user.

**Comment by Claire-serveth** [comment]
Hi @liliya-soroka already got the response from the user and he is using Ledger Nano X (and only meant using Ledger Nano when he said ledger module). Also, remove transaction was done on the UI and not via contract interaction. That is,

1. User connected ledger via direct ledger connection/button on the UI
2. Remove owner from the settings
3. On the confirm page, Execute/sign button is greyed out and getting this error: 
_This transaction will most likely fail. To save gas costs, avoid confirming the transaction.
The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up._

**Comment by liliya-soroka** [comment]
Could you point me to the intercom conversation, please?

**Comment by Claire-serveth** [comment]
HI @liliya-soroka here's the intercom link: https://app.eu.intercom.com/a/inbox/pynbtguw/inbox/admin/50011286/conversation/212174700008840?view=List

**Comment by Claire-serveth** [comment]
Intercom ticket was already assigned to Rudy.

**Comment by Claire-serveth** [comment]
Closing this issue as advised by Rudy.
